In [1]:
# Add the project root directory to sys.path to enable imports from the project
import sys
from pathlib import Path

project_root = Path().resolve().parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

In [2]:
import duckdb
from constants.db import STAGE_3_DB

In [3]:
with duckdb.connect(str(STAGE_3_DB)) as connection:
    tables = connection.sql("SHOW ALL TABLES").df()
tables

,database,schema,name,column_names,column_types,temporary
0,stage_3,stage_3_dev,int__farms,"[parksid, jurisdiction, address, cross_streets...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, BIGINT, B...",False
1,stage_3,stage_3_dev,stg__boroughs,"[boro_name, boro_code, geom]","[VARCHAR, VARCHAR, GEOMETRY]",False
2,stage_3,stage_3_dev,stg__garden_block_lot,"[parksid, block, lotnum, lotsize, areacovered]","[VARCHAR, BIGINT, BIGINT, DOUBLE, VARCHAR]",False
3,stage_3,stage_3_dev,stg__garden_info,"[parksid, gardenname, jurisdiction, borough, a...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ...",False
4,stage_3,stage_3_dev,stg__markets,"[market_name, accepts_ebt, distributes_health_...","[VARCHAR, VARCHAR, BOOLEAN, VARCHAR, VARCHAR, ...",False
5,stage_3,stage_3_dev__tests,farm_to_market_compound_key,"[market_name, farm_name, distance_ft]","[VARCHAR, VARCHAR, INTEGER]",False
6,stage_3,stage_3_dev__tests,not_null_farm_to_market_distance_ft,"[market_name, farm_name, distance_ft, line_geo...","[VARCHAR, VARCHAR, INTEGER, GEOMETRY]",False
7,stage_3,stage_3_dev__tests,not_null_farm_to_market_farm_name,"[market_name, farm_name, distance_ft, line_geo...","[VARCHAR, VARCHAR, INTEGER, GEOMETRY]",False
8,stage_3,stage_3_dev__tests,not_null_farm_to_market_line_geometry_wgs84,"[market_name, farm_name, distance_ft, line_geo...","[VARCHAR, VARCHAR, INTEGER, GEOMETRY]",False
9,stage_3,stage_3_dev__tests,not_null_farm_to_market_market_name,"[market_name, farm_name, distance_ft, line_geo...","[VARCHAR, VARCHAR, INTEGER, GEOMETRY]",False
10,stage_3,stage_3_dev__tests,not_null_farms_farm_name,[farm_name],[VARCHAR],False
11,stage_3,stage_3_dev__tests,not_null_markets_market_name,[market_name],[VARCHAR],False
12,stage_3,stage_3_dev__tests,source_not_null_external_sourc_d6702d345bd09d6...,"[Borough, Market Name, Street Address, Communi...","[VARCHAR, VARCHAR, VARCHAR, BIGINT, DOUBLE, DO...",False
13,stage_3,stage_3_dev__tests,source_not_null_external_source_Borough_Bounda...,"[borocode, boroname, shape_area, shape_leng, g...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, GEOMETRY]",False
14,stage_3,stage_3_dev__tests,source_not_null_external_source_GreenThumb_Blo...,"[parksid, block, lotnum, lotsize, areacovered]","[VARCHAR, BIGINT, BIGINT, DOUBLE, VARCHAR]",False
15,stage_3,stage_3_dev__tests,source_not_null_external_source_GreenThumb_Gar...,"[assemblydist, address, borough, communityboar...","[BIGINT, VARCHAR, VARCHAR, BIGINT, BIGINT, BIG...",False
16,stage_3,stage_3_dev__tests,source_unique_external_source_Borough_Boundari...,"[unique_field, n_records]","[GEOMETRY, BIGINT]",False
17,stage_3,stage_3_dev__tests,source_unique_external_source_GreenThumb_Garde...,"[unique_field, n_records]","[VARCHAR, BIGINT]",False
18,stage_3,stage_3_dev__tests,source_unique_external_source_NYC_Farmers_Mark...,"[unique_field, n_records]","[VARCHAR, BIGINT]",False
19,stage_3,stage_3_dev_product,farm_to_market,"[market_name, farm_name, distance_ft, line_geo...","[VARCHAR, VARCHAR, INTEGER, GEOMETRY]",False
20,stage_3,stage_3_dev_product,farms,[farm_name],[VARCHAR],False
21,stage_3,stage_3_dev_product,markets,[market_name],[VARCHAR],False

In [4]:
product_tables = tables[tables.schema == "stage_3_dev_product"]
product_tables

,database,schema,name,column_names,column_types,temporary
19,stage_3,stage_3_dev_product,farm_to_market,"[market_name, farm_name, distance_ft, line_geo...","[VARCHAR, VARCHAR, INTEGER, GEOMETRY]",False
20,stage_3,stage_3_dev_product,farms,[farm_name],[VARCHAR],False
21,stage_3,stage_3_dev_product,markets,[market_name],[VARCHAR],False